


function calculateInterest(){    
    const tipeInterest =  document.getElementsByName('tipeInterest');
    //console.log("El valor de tipoInteres es de: " + tipoInteres);
    let validate;
    // just checked the value selected in the radio section
    for (var i = 0, length = tipeInterest.length; i < length; i++) {
        if (tipoInterest[i].checked) {
            validate = tipeInterest[i].value;
            //alert(tipoInteres[i].value);
            // only one radio can be logically checked, don't check the rest
            break;
        }
    }

    if(validate==="1"){
        //console.log("Se escogió interés simple D:")
        const inputCapital = document.getElementById("Capital");
        const Capital = parseInt(inputCapital.value);
    
        const inputInterest = document.getElementById("Interest");
        const Interest = parseFloat(inputInterest.value);
    
        const inputTime = document.getElementById("Time");
        const Time = parseInt(inputTime.value);

        let Result = Capital * Interest * Time/100;

        const resultP = document.getElementById("ResultP");
        resultP.innerText = "The total interest generated by simple interest is: $" + Result;
        /* if(Time === 3){
            console.log("Pass as int");

        }
        else if(Time == 3){
            console.log("Pass as string");
        }
        else{
            console.log("Nothing happend :,( ");
        }  */

    }
    else{
        const inputCapital = document.getElementById("Capital");
        const Capital = parseFloat(inputCapital.value);
    
        const inputInterest = document.getElementById("Interest");
        const Interest = parseFloat(inputInterest.value);
    
        const inputTime= document.getElementById("Time");
        const Time = parseInt(inputTime.value);

        let resultFinalCapital = Capital * (1+(Interest/100))**(Time);
        
        let interestWithoutInitial = resultFinalCapital - Capital;
        const resultP = document.getElementById("ResultP");
        resultP.innerText = "The total interest generated by compound interest is: $" + interestWithoutInitial;
    }
}